### ISSUE TITLE
Application for Product ID

### ISSUE THREAD

**Issue by grzegorz-kraszewski** [oahr/oahr#1]
# My Project

* Project Name: KA12 serial port MIDI interface
* Name of the maker or the team: RastPort
* URL of the source code: https://github.com/grzegorz-kraszewski/rastport
* Open Source License: Creative Commons Attribution 4.0 International

Photos on https://rastport.com/products/KA12/
Project status: production

# Product IDs

KA12 does not use AutoConfig of course, so Product ID is not needed.

# Further Questions

* [x] I have read and understood [the rules](https://oahr.github.io/oahr/application.html#the-rules).
* [ ] This is a fork of another open hardware project. (Please state which one.)
* [ ] This is an extension of a project that is already registered with OAHR. (Please state which one.)

**Comment by shred** [comment]
Added to the list. Thank you for your contribution!
